#!/bin/bash
#
# Author: Chris Jones <cjones303@bloomberg.net>
# Copyright 2015, Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### OLD

set -e

# Clone VMs to make working on Chef portion faster. No need to rebuild. Instead, run vbox_reverse_cloning_vms.sh

export REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/bootstrap/vms/vbox_functions.sh
source $REPO_ROOT/bootstrap/vms/ceph_chef_hosts.env
source $REPO_ROOT/bootstrap/vms/ceph_chef_adapters.env
source $REPO_ROOT/bootstrap/vms/ceph_chef_bootstrap.env

# All to locations originate from the vagrant /home/vagrant user location

vm=$1
from=$2
to=$3

if [[ `is_vm_running $vm` -ne 1 ]]; then
    echo "$vm was not found as a valid VM."
    exit 1
fi

ssh_port=$(get_vm_ssh_port $vm)
if [[ ssh_port -gt 0 ]]; then
    if [[ ! -z $from && ! -z $to ]]; then
        scp -p $ssh_port -i $REPO_ROOT/bootstrap/vms/chef-bcs $from vagrant@127.0.0.1:$to
    else
        echo "Requires a <from> and <to>"
    fi
else
    echo "$vm does not appear to have a valid ssh port - $ssh_port"
fi
